### ISSUE TITLE
Invalid precision when running train_project_gutenberg

### ISSUE THREAD

**Issue by erlebach** [fkodom/yet-another-retnet#13]
I am running on the mac, and like the clarity of your code. My device is 'cpu', since I don't have Cuda on a mac notebook. Running `retnet.py` works fine. However, when running `train_project_gutenburg` using the command: 
```
python -m scripts.train_project_gutenberg
```
I get the following trace: 
```
Traceback (most recent call last):
  File "/Users/erlebach/opt/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/erlebach/opt/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/scripts/train_project_gutenberg.py", line 388, in <module>
    main(**vars(args))
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/scripts/train_project_gutenberg.py", line 349, in main
    train(
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/scripts/train_project_gutenberg.py", line 205, in train
    fabric = Fabric(
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/.venv/lib/python3.10/site-packages/lightning/fabric/fabric.py", line 127, in __init__
    self._connector = _Connector(
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/.venv/lib/python3.10/site-packages/lightning/fabric/connector.py", line 135, in __init__
    self._check_config_and_set_final_flags(
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/.venv/lib/python3.10/site-packages/lightning/fabric/connector.py", line 229, in _check_config_and_set_final_flags
    precision_input = _convert_precision_to_unified_args(precision)
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/.venv/lib/python3.10/site-packages/lightning/fabric/connector.py", line 559, in _convert_precision_to_unified_args
    raise ValueError(f"Precision {repr(precision)} is invalid. Allowed precision values: {supported_precision}")
ValueError: Precision 'float32' is invalid. Allowed precision values: ('transformer-engine', 'transformer-engine-float16', '16-true', '16-mixed', 'bf16-true', 'bf16-mixed', '32-true', '64-true', 64, 32, 16, '64', '32', '16', 'bf16')
```
What is non-standard in the current code that is preventing this from happening? Thanks.

**Comment by fkodom** [comment]
I'm away from my computer right now, but looks like I set the wrong default value (`float32` instead of the correct value `32-true`).  Will fix asap once I'm back.  You can also pass `--precision 32-true` to the training script as a temporary workaround.

**Comment by erlebach** [comment]
I fixed the issue, and you might wish to do the same: 
```
    if precision is None:
        if torch.cuda.is_available():
            # use bfloat16 if supported
            version, _ = torch.cuda.get_device_capability()
            precision = "bf16-mixed" if version >= 8 else "16-mixed"
        else:
            #precision = "float32"
            precision = "32"  # for CPU
```
in `train_project_gutenberg.py`. I am running on the CPU, and `float32` fails, at least on a mac notebook running the M2 chip.
