### ISSUE TITLE
Running benchmark_inference on the CPU

### ISSUE THREAD

**Issue by erlebach** [fkodom/yet-another-retnet#17]
I am running scripts/benchmark_inference on the CPU (on a Mac M2 with Ventura OS). There are several issues with the code: 
Could you please run the code on the CPU with a version of Torch which does not have CUDA?  Or amend the README file stating the constraints on the code? 

Thanks.

- I added the following section after DEVICE definition: 
```
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if DEVICE == 'cuda':
    DTYPE = torch.float16
else:
    DTYPE = torch.float32
print(DEVICE)
```
I disabled the call to `benchmark_inference_memory`. The function calls `Profile`, which depends on the a version of PyTorch with GPU enabled. Perhaps you could fix the code? 

- For some reason, the lines:
```
        # Benchmark *recurrent* RetNet formulation for inference
        retnet_result = benchmark(
            retnet.forward_recurrent, x[:, 0], seq_idx=0, prev_states=[]
        )
```
generate the message: 
```
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
```
Here is the full trace (the line numbers in benchmark_inference might be off by 3-4 lines because of my additions at the top of the code. 
```
Traceback (most recent call last):
  File "/Users/erlebach/opt/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/erlebach/opt/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/scripts/benchmark_inference.py", line 165, in <module>
    retnet_throughputs, transformer_throughputs = benchmark_inference_throughput(
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/scripts/benchmark_inference.py", line 109, in benchmark_inference_throughput
    retnet_result = benchmark(
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/yet_another_retnet/utils/benchmark.py", line 43, in benchmark
    _ = timer.repeat(number=1, repeat=5)
  File "/Users/erlebach/opt/miniconda3/lib/python3.10/timeit.py", line 206, in repeat
    t = self.timeit(number)
  File "/Users/erlebach/opt/miniconda3/lib/python3.10/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 686, in synchronize
    _lazy_init()
  File "/Users/erlebach/src/2023/retentive_networks/retentive_code/yet-another-retnet/.venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
```

**Comment by fkodom** [comment]
@erlebach The `benchmark` function was failing due to `torch.cuda.synchronize()`, which was used under the hood.  I made [a quick patch](https://github.com/fkodom/yet-another-retnet/pull/19), so that it won't call that function if `not torch.cuda.is_available()`.

The `profile` function is more involved, since it was explicitly written for monitoring CUDA memory.  As a temporary workaround, I just skipped GPU memory profiling is CUDA is not available.  I assume you could do [something similar to this](https://github.com/fkodom/yet-another-retnet/blob/71aa28988d1ce25150b2faec32635af287bac9d5/yet_another_retnet/utils/profile.py#L51-L56), but using `psutil` instead:
```python
import psutil
available_memory = psutil.virtual_memory().available
```
